import SliderImg1 from "./images/slide1.jpg";
import SliderImg2 from ".//images/slide2.jpg";
import SliderImg3 from "./images/slide3.jpg";
import OverviewImg from "./images/overview.jpg";
import ApproachImg1 from "./images/approach1.svg";
import ApproachImg2 from "./images/approach2.svg";
import ApproachImg3 from "./images/approach3.svg";
import ApproachImg4 from "./images/approach4.svg";
import ApproachImg5 from "./images/approach5.svg";
import ApproachImg6 from "./images/approach6.svg";
import AboutImg from "./images/about.jpg";
import ContactImg from "./images/contact.jpg";
import BlogImg from "./images/blog.jpg";
import ComingSoonImg from "./images/coming-soon.jpg";
import WhoWeAreImg from "./images/who-we-are1.jpg";
import TeamImg from "./images/team.jpeg";
import PostImg from "./images/posts.webp";
import InsightImg2 from "./images/insights.webp";
import BlogImg2 from "./images/blog.webp";
import SupportImg from "./images/support.jpg";
import EhiobaImg from "./images/ehioba.jpeg";
import TwitterX from "./images/twitterx.jpg";
import Partners from "./images/partners.jpg";
import Partner1 from "./images/partner1.png";

export const LOGO =
	"https://res.cloudinary.com/dk9bt9lkn/image/upload/v1692541421/ehioba/Ehioba_green_3_hiylnr.png";
export const SLIDER_IMAGE_1 = SliderImg1;
export const SLIDER_IMAGE_2 = SliderImg2;
export const SLIDER_IMAGE_3 = SliderImg3;
export const OVERVIEW_IMAGE = OverviewImg;
export const APPROACH_IMAGE_1 = ApproachImg1;
export const APPROACH_IMAGE_2 = ApproachImg2;
export const APPROACH_IMAGE_3 = ApproachImg3;
export const APPROACH_IMAGE_4 = ApproachImg4;
export const APPROACH_IMAGE_5 = ApproachImg5;
export const APPROACH_IMAGE_6 = ApproachImg6;
export const ABOUT_IMAGE = AboutImg;
export const CONTACT_IMAGE = ContactImg;
export const BLOG_IMAGE = BlogImg;
export const INSIGHTS_IMAGE = BlogImg;
export const COMING_SOON = ComingSoonImg;
export const WHO_WE_ARE = WhoWeAreImg;
export const TEAM = TeamImg;
export const POSTS_IMG = PostImg;
export const INSIGHTS_IMG = InsightImg2;
export const BLOG_IMG = BlogImg2;
export const SUPPORT_IMG = SupportImg;
export const EHIOBA_IMG = EhiobaImg;
export const TwitterXImg = TwitterX;
export const PARTNERS_IMG = Partners;
export const PARTNER1 = Partner1;
